makeT: Globals.cpp pattern.cpp SO6.cpp Z2.cpp main.cpp
	/opt/ohpc/pub/compiler/gcc/9.3.0/bin/g++ -I/opt/ohpc/pub/libs/gnu9/openmpi4/boost/1.73.0/include  main.cpp SO6.cpp Z2.cpp pattern.cpp Globals.cpp -std=c++11 -pthread -O3 -o main.out -fopenmp -march=znver2 -L/opt/ohpc/pub/libs/gnu9/openmpi4/boost/1.73.0/lib -lboost_program_options 
##	g++ main.cpp SO6.cpp Z2.cpp pattern.cpp -std=c++11 -pthread -O3 -o main.out -fopenmp
